#!/usr/bin/env bun
/**
 * Generates the EdDSA (Ed25519) key material the self-hosted Stofloos relay needs.
 *
 * Emits two keypairs as single-line PEM (with literal `\n`) suitable for pasting
 * into `.env` / Docker secrets:
 *   - cloud mint keypair  -> signs DPoP access tokens + link challenges (RelayTokens)
 *   - auth session keypair -> signs login session JWTs (relay-as-IdP)
 *
 * Keys are PKCS8 (private) / SPKI (public) PEM, matching `@t3tools/shared/relayJwt`.
 *
 * Usage: `bun scripts/gen-keys.ts`
 */
import { generateKeyPairSync } from "node:crypto";

function makeEd25519Pair(): { readonly privateKey: string; readonly publicKey: string } {
  const { privateKey, publicKey } = generateKeyPairSync("ed25519", {
    privateKeyEncoding: { type: "pkcs8", format: "pem" },
    publicKeyEncoding: { type: "spki", format: "pem" },
  });
  return { privateKey: privateKey.toString(), publicKey: publicKey.toString() };
}

function toEnvValue(pem: string): string {
  // Store PEM as a single line with escaped newlines; relayJwt.normalizePem() restores them.
  return `"${pem.trim().replace(/\n/gu, "\\n")}"`;
}

const cloudMint = makeEd25519Pair();
const authSession = makeEd25519Pair();

const lines = [
  "# Generated by scripts/gen-keys.ts — keep the private keys secret.",
  `RELAY_CLOUD_MINT_PRIVATE_KEY=${toEnvValue(cloudMint.privateKey)}`,
  `RELAY_CLOUD_MINT_PUBLIC_KEY=${toEnvValue(cloudMint.publicKey)}`,
  `RELAY_AUTH_SESSION_PRIVATE_KEY=${toEnvValue(authSession.privateKey)}`,
  `RELAY_AUTH_SESSION_PUBLIC_KEY=${toEnvValue(authSession.publicKey)}`,
];

process.stdout.write(`${lines.join("\n")}\n`);
